server {
  server_name stuff.rnieb.dev; # the domain we access this with

  listen 80; # listen on this port
  client_max_body_size 32m; # max 32mb post; same as backend

  # serve react app
  location / {
    root /usr/share/nginx/html;
    try_files 
      $uri  # match static assets
      $uri/ # match file inside route ( convention; not needed for react )
      /index.html; # fallback to the index file ( matches regular routes )
  }

  # proxy api calls to the backend
  location /api/ {
    proxy_pass http://backend:8080;
  }
}
