# redirect server config
server {
  listen 80; # listens on regular http port 
  server_name stuff.rnieb.dev; # the domain name 

  # redirect any http request to https
  return 301 https://$host$request_uri; # return <statuscode> <redirect>
}

# main server config
server {
  listen 443 ssl; # listen on ssl port
  
  # ssl keyword tells nginx to look for certs and handle conn as tls

  server_name stuff.rnieb.dev; # the domain name 

  client_max_body_size 32m; # max 32mb post; same as backend

  # serve react app
  location / {
    root /usr/share/nginx/html;
    try_files 
      $uri  # match static assets
      $uri/ # match file inside route ( convention; not needed for react )
      /index.html; # fallback to the index file ( matches regular routes )
  }

  # proxy api calls to the backend
  location /api/ {
    proxy_pass http://backend:8080;
  }

  # SSL CONFIGURATION FOR HTTPS

  # ran certbot to get it on the main vps
  # mounted /etc/letsencrypt via docker compose vlm mnt

  ssl_certificate /etc/letsencrypt/live/stuff.rnieb.dev/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/stuff.rnieb.dev/privkey.pem;

  # this reminds me of my internship at lutron :)
}
