server {
  listen 80; # listen on this port

  # serve react app
  location / {
    root /usr/share/nginx/html;
    try_files 
      $uri  # match static assets
      $uri/ # match file inside route ( convention; not needed for react )
      /index.html; # fallback to the index file ( matches regular routes )
  }

  # proxy api calls to the backend
  location /api/ {
    proxy_pass http://backend:8080;
  }
}
