name: Deploy
on:
  push:
    branches:
      - main # how/why can we redeploy from many branches?
jobs:
  deploy:
    runs-on: ubuntu-latest # os github actions runner will use
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1 # plugin that does ssh for us
        with: # args given to ssh-action
          host: ${{ secrets.SERVER_HOST }} #
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: | # all of this is standard stuff we do by hand
            cd /root/rnieb/
            git pull
            docker compose up --build -d

# ${{}} syntax is gh action specific for injecting runtime val
# | is yaml multiline syntax
